#!/usr/bin/env bash
#Configure your Nginx server so that /redirect_me is redirecting to another page.
#The redirection must be a “301 Moved Permanently”
STRING="Hello World!"
REDIRECT="server_name _;\n\nlocation /redirect_me/ {\n\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n"
FILE="/etc/nginx/sites-available/default"
sudo apt -y update
sudo apt -y install nginx
sudo chown -R "$USER:$USER" /var/www/
sudo ufw allow 'Nginx HTTP'
echo "$STRING" > /var/www/html/index.nginx-debian.html
sudo sed -i "s|server_name _;|$REDIRECT|" $FILE

CONF="/etc/nginx/nginx.conf"
HEADER='http {\n\t\t=add_header X-Served-By $HOSTNAME;'
sudo sed -i "s|http {|$HEADER|" $CONF
sudo service nginx restart
