#!/usr/bin/env bash
sudo apt update
sudo apt -y upgrade
sudo apt -y install haproxy
server1="server 80605-web-01 3.94.181.17:8080 check"
server2="server 80605-web-02 54.157.165.12:8080 check"
frontend = "\nfrontend haproxynode\n\tbind *:80\n\tmode http\n\tdefault_backend backendnodes\n"
backend = "\nbackend backendnodes\n\tbalance roundrobin\n\t$server1\n$server2

sudo echo "$frontend$backend" >> /etc/haproxy/haprogy.cfg
