#!/usr/bin/env bash
# Install and configure HAproxy
sudo apt update -y
apt-get install --no-install-recommends software-properties-common
add-apt-repository ppa:vbernat/haproxy-2.7

#sudo sed -i "s|ENABLED=0|ENABLED=1|g" /etc/default/haproxy
sudo sed -i "\$aENABLED=1\n" /etc/default/haproxy

FRONT_END="frontend http_front\n\tbind *:80\n\tmode http\n\tdefault_backend http_back\n"

BACK_END="backend http_back\n\tbalance roundrobin\n\tserver 80605-web-01 3.94.181.17:80 check\n\tserver 80605-web-02 54.157.165.12:80 check\n"
sudo sed -i "\$a$FRONT_END\n$BACK_END" /etc/haproxy/haproxy.cfg
sudo service haproxy restart
