#!/usr/bin/env bash
# a bash script that displays a list of currently running processes
# must show all processes, for all users, including those that might not have a TTY
# display in a user-oriented format
# show process hierarchy

ps -auxf
