#!/bin/bash

# Get the process IDs of the Gunicorn workers
worker_pids=$(ps aux | grep '[g]unicorn' | awk '{print $2}')

# Send a graceful reload signal to each worker
for pid in $worker_pids; do
    kill -HUP "$pid"
done